
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/klippan?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

    username: root
    password: 117028Nur
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true





server:
  port: 8081
